name: Sales by country and year
description: Revenue by user country and order year
tableName: fct_orders
updatedAt: "2026-01-28T15:38:16.492Z"
metricQuery:
  exploreName: fct_orders
  dimensions:
    - fct_orders_user_country
    - fct_orders_order_date_year
  metrics:
    - fct_orders_amount_sum_of_amount
  filters: {}
  sorts:
    - fieldId: fct_orders_order_date_year
      descending: false
    - fieldId: fct_orders_amount_sum_of_amount
      descending: true
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics:
    - name: amount_sum_of_amount
      label: Sum of Amount
      description: "Sum of Amount on the table Fct orders"
      sql: ${TABLE}.amount
      table: fct_orders
      type: sum
      baseDimensionName: amount
      formatOptions:
        type: default
        separator: default
  customDimensions: []
chartConfig:
  type: cartesian
  config:
    layout:
      xField: fct_orders_order_date_year
      yField:
        - fct_orders_amount_sum_of_amount
      flipAxes: false
      showLegend: true
    eChartsConfig:
      series:
        - type: bar
          encode:
            xRef:
              field: fct_orders_order_date_year
            yRef:
              field: fct_orders_amount_sum_of_amount
slug: sales-by-country-year
tableConfig:
  columnOrder:
    - fct_orders_user_country
    - fct_orders_order_date_year
    - fct_orders_amount_sum_of_amount
spaceSlug: main
version: 1
downloadedAt: "2026-01-28T15:38:22.761Z"
