name: unique customers by country
description: "Уникальные клиенты по странам"
tableName: fct_orders
updatedAt: "2026-02-05T12:00:00.000Z"
metricQuery:
  exploreName: fct_orders
  dimensions:
    - fct_orders_user_country
  metrics:
    - fct_orders_unique_customers
  filters: {}
  sorts:
    - fieldId: fct_orders_unique_customers
      descending: true
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: cartesian
  config:
    layout:
      stack: none
      xField: fct_orders_user_country
      yField:
        - fct_orders_unique_customers
      flipAxes: true
    eChartsConfig:
      series:
        - type: bar
          encode:
            xRef:
              field: fct_orders_user_country
            yRef:
              field: fct_orders_unique_customers
          yAxisIndex: 0
          isFilteredOut: false
      showAxisTicks: false
slug: unique-customers-by-country
tableConfig:
  columnOrder:
    - fct_orders_user_country
    - fct_orders_unique_customers
spaceSlug: shared
version: 1
downloadedAt: "2026-02-05T12:00:00.000Z"
